/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clicktocrypt;

import javax.swing.JFrame;

/**
 *
 * @author Maciej
 */
public class CTCMain extends javax.swing.JFrame {

    
      CryptoFunctions cf;
    
    /**
     * Creates new form CTCMain
     */
    public CTCMain() {
        
        initComponents();
         
         cf = new CryptoFunctions();
        
        
        
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        TextCryptoKey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextCryptoInput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Button_Encrypt = new javax.swing.JButton();
        Button_Decrypt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextCryptoOutput = new javax.swing.JTextArea();
        Text_Error_Message = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Click and Crypt");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Key:");

        TextCryptoKey.setToolTipText("");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TextCryptoInput.setColumns(20);
        TextCryptoInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextCryptoInput.setLineWrap(true);
        TextCryptoInput.setRows(5);
        TextCryptoInput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TextCryptoInput);

        jLabel2.setText("Text:");

        Button_Encrypt.setText("Encrypt");
        Button_Encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EncryptActionPerformed(evt);
            }
        });

        Button_Decrypt.setText("Decrypt");
        Button_Decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DecryptActionPerformed(evt);
            }
        });

        TextCryptoOutput.setEditable(false);
        TextCryptoOutput.setColumns(20);
        TextCryptoOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextCryptoOutput.setLineWrap(true);
        TextCryptoOutput.setRows(5);
        TextCryptoOutput.setWrapStyleWord(true);
        jScrollPane2.setViewportView(TextCryptoOutput);

        Text_Error_Message.setText("Ready");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Button_Encrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(Button_Decrypt)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text_Error_Message, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(TextCryptoKey, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextCryptoKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Encrypt)
                    .addComponent(Button_Decrypt))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Error_Message, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_EncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EncryptActionPerformed
       

        
            cf.create_key(TextCryptoKey.getText());

            TextCryptoOutput.setText(cf.encrypt(TextCryptoInput.getText()));

            Text_Error_Message.setText(cf.last_error_code);
            
   
         
        
    }//GEN-LAST:event_Button_EncryptActionPerformed

    private void Button_DecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DecryptActionPerformed
             

            cf.create_key(TextCryptoKey.getText());
            TextCryptoOutput.setText(cf.decrypt(TextCryptoInput.getText()));


            
            Text_Error_Message.setText(cf.last_error_code);

    }//GEN-LAST:event_Button_DecryptActionPerformed

    
    public void set_error_code(String error_text)
    {
        
        Text_Error_Message.setText(error_text);
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTCMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTCMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTCMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTCMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTCMain().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Decrypt;
    private javax.swing.JButton Button_Encrypt;
    private javax.swing.JTextArea TextCryptoInput;
    private javax.swing.JTextField TextCryptoKey;
    private javax.swing.JTextArea TextCryptoOutput;
    private javax.swing.JLabel Text_Error_Message;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
